### PR TITLE
Issue 169 Spacing Glosses

### PR DESCRIPTION
**Pull request by KamBustos**
There is a bug where if there is an additional space after searching for a gloss, it will not find or filter that gloss out. This occurs in the deer-config file. A proper fix would make it so that no matter how many spaces there are after the gloss is typed in, it still properly searches.

This is the bug for glossing.html:

Picture of Bug:

image
Picture of Fix:

issue169

I also fixed this on the gloss-transcription.html side.

Picture of Bug:

image

Picture of Fix:

spacing_issue

### CODE REVIEW

**Comment by AbhilashKotha** [comment]
Hi @KamBustos, I tested this and it works fine in glossing.html. but it doesn't work in gloss-transcription.html. Could you please look into that? Thanks.

**Comment by AbhilashKotha** [comment]
Works well now. Good work Kameron :)

**Review by thehabes — CHANGES_REQUESTED** [review]
The template refactor has come in upstream from you.  Please resolve merge conflicts, then I can come back around to test this.

**Review by thehabes — CHANGES_REQUESTED** [review]
Nice, this is a common thing that users do and it is  a good idea to handle it.  It doesn't need to be any more difficult on you or more complex than trim(), you got it.

This worked correctly on glosses.html and gloss-transcription.html.  However, it did not work on manage-glosses.html

image

Adding the space...

image

Make sure that interface works as well, it should be pretty much the same code.  Test it and send it back when you're sure it is working.

**Review by thehabes — APPROVED** [review]
No fun to have to C & P across all these filterGlosses(), we will get into the Gloss List and Gloss List Item templates one day and reduce this.

Works in all the templates for me, good to go!

**Pull request merged**
