### PR TITLE
Issue 80 - Hard crash on failed rerum queries

### PR DESCRIPTION
**Pull request by cohen-j**
I went through shared.js and tried to find spots where errors are caught within `fetch` functions to bring up an alert like the image below (like Bryan showed in Thursday's meeting). However, I'm having trouble actually triggering globalFeedbackBlips from query errors. 

This is how it _should_ look - I just did this using the in-browser developer console.
image

### CODE REVIEW

**Comment by cohen-j** [comment]
image

A globalFeedbackBlip now appears when a query is failed on every part of the site (see above). As far as I know, these changes cover all the bases in terms of failed queries (I just looked for where `fetch` was used and inserted a globalFeedbackBlip in the following `catch`) 

If I missed something, please comment or ping me in Slack so I can fix.

**Comment by cohen-j** [comment]
@AbhilashKotha I have implemented specific messages per status code along with a generalized error message for other, unforeseen status codes. See `handleErrorBlip` function in _deer-utils.js_ as well as the previous places in _deer-record.js_ and _deer-render.js_ where I had caught errors.

**Review by AbhilashKotha — APPROVED** [review]
lgtm;

**Review by thehabes — APPROVED** [review]
Looks good, I tested it a handful of ways and got the messages I expected.

One flaw is that after the blip disappears, the user is left starting at an infinite `Loading...` message sometimes.  If we get user feedback about this, we may consider a blip that remains on screen instead of disappearing for certain errors.

**Pull request merged**
