### PR TITLE
Issue #141 Created new form for adding an external reference to a gloss or manuscript

### PR DESCRIPTION
**Pull request by TheTuTran**
PR for https://github.com/CenterForDigitalHumanities/glossing-entries/issues/141

Added a temp.html and rich text editor to see what the form would look like:
image

- Self contained form with necessary JavaScript in <script> tags underneath for the form.
- Contains a vanilla rich text editor
- Grabs URI from page link (if available), otherwise creates a null reference
- Checks against the document reference to see if valid URI according to issue requirements

### CODE REVIEW

**Comment by AbhilashKotha** [comment]
@TheTuTran I do not see Subscript or superscript options. Can you include those options too?

**Comment by AbhilashKotha** [comment]
@TheTuTran After testing with a few more scenarios, I found that the form can accept images which I think should not be the case. @thehabes @cubap Please correct me if I am wrong.

image

**Comment by cubap** [comment]
It is not expected, but not explicitly wrong. I suspect it is an image element so it is linking the image, not actually saving it.

**Review by AbhilashKotha — APPROVED** [review]

**Comment by AbhilashKotha** [comment]
The required form is loading fine. Text formatting is working fine.

**Review by cubap — APPROVED** [review]
unchecked. We're approving on trust.

**Pull request merged**
