### PR TITLE
55 - README

### PR DESCRIPTION
**Pull request by cohen-j**
Added some initial changes to `README.md`. Not completely satisfied with the wording yet - may change some of that. 

Information regarding actual data entry still needs to be added (e.g., new glosses, detect glosses...)

image

### CODE REVIEW

**Comment by cohen-j** [comment]
The above image _may_ have the wrong hyperlinks for the data entry site. it has been fixed now by the most recent push.

**Comment by cohen-j** [comment]
image
finished writing the readme, any suggestions?

**Review by AbhilashKotha — APPROVED** [review]
All the required sections are included. the instructions seem clear to me!

**Review by thehabes — APPROVED** [review]
Amazing, I appreciate it.   This would be something to bring to Atria's attention or the attention to the other students actually using the app.  Their feedback would be valuable here, and maybe you can even tempt them to write some for us as more functionality becomes available.

**Pull request merged**
