### PR TITLE
Approximate Match

### PR DESCRIPTION
**Pull request by xXCrash2BomberXx**

### CODE REVIEW

**Review by thehabes — CHANGES_REQUESTED** [review]
It does not seem to capture the "the glosses are done loading" event.  I started by clicking to refresh the cached glosses and this was the original UI.

image

This was the UI after the final gloss loaded
image

This was the UI after I reloaded the page.
image

I expect the options for approximate search to appear once the Glosses are done loading so that the last two examples have matching UIs.

**Review by AbhilashKotha — APPROVED** [review]
I tested a few scenarios that I could think of and it works fine. @thehabes Could you please provide your comments.

**Review by thehabes — CHANGES_REQUESTED** [review]
I am seeing an error in my web console when I uncheck the first box.

image

**Review by thehabes — CHANGES_REQUESTED** [review]
I have noticed another breaking change while testing.

The points of the "glosses" interface is to show the user the gloss they are looking for as quickly as possible.  When you go to 
https://glossing.rerum.io/glosses.html?gog-filter=JTdCJTIydGl0bGUlMjIlM0ElMjJxdWFzaSUyMiUyQyUyMnRleHQlMjIlM0ElMjJxdWFzaSUyMiUyQyUyMnRhcmdldGVkdGV4dCUyMiUzQSUyMnF1YXNpJTIyJTdE 
and [Click Here] to reset the gloss cache, the entries matching the filter "quasi" are shown as soon as they load
 
image

Yours does the same thing, which is good.  
https://glossing.rerum.io/glosses.html?gog-filter=JTdCJTIydGl0bGUlMjIlM0ElMjJxdWFzaSUyMiUyQyUyMnRleHQlMjIlM0ElMjJxdWFzaSUyMiUyQyUyMnRhcmdldGVkdGV4dCUyMiUzQSUyMnF1YXNpJTIyJTdE
image

To test Approximate Search, I changed to term to "qvasi", which shows me these entries before I empty the cache to reload, which again is correct.

image

However, I did not see these Glosses appear as part of the loading process until **_all_** Glosses were loaded.  I expected to see the matches appear as they loaded like they did for "quasi".  It does not seem Approximate Search inherited the correct "show it as it loads" behavior.
http://localhost:8080/glosses.html?gog-filter=JTdCJTIydGl0bGUlMjIlM0ElMjJxdmFzaSUyMiUyQyUyMnRleHQlMjIlM0ElMjJxdmFzaSUyMiUyQyUyMnRhcmdldGVkdGV4dCUyMiUzQSUyMnF2YXNpJTIyJTdE

image

This is considered a breaking change.  The instructions say "Gloss filter detected. Please note that Glosses will appear as they are fully loaded." and "You may click to select any Gloss loaded already"

**Review by thehabes — CHANGES_REQUESTED** [review]
I am still experiencing strange "reordering behavior".

After the Glosses load, here is the list I see
image

Here is the list after I search for 'quasi'
image

And here's the list after I remove 'quasi' from the query.  You'll notice they are in a different order than they were at page load, even though there is no search query.  

image

Production does not behave this way.  When I do the same test there, I see the same Glosses in the same order as they were on page load.  Unless the reorder is a new feature, this is not a desirable effect.

I'll leave it up to @AbhilashKotha to decide what to do.  It doesn't break anything, but it is unexpected behavior.

**Pull request merged**
