### PR TITLE
Table glosses

### PR DESCRIPTION
**Pull request by xXCrash2BomberXx**

### CODE REVIEW

**Review by AbhilashKotha — COMMENTED** [review]
works well for me. @thehabes Could you please provide your review for this PR.

**Review by AbhilashKotha — COMMENTED** [review]
I am seeing this when I load the glosses. it wasn't the case before. 
- I see untitled for glosses that have a reference.
- I see untitled for glosses that do not have a ref
- I see 99:_ for some glosses

Screenshot 2024-04-08 at 12 04 35 AM

**Comment by xXCrash2BomberXx** [comment]
> I am seeing this when I load the glosses. it wasn't the case before. 
> - I see untitled for glosses that have a reference.
> - I see untitled for glosses that do not have a ref
> - I see 99:_ for some glosses
> 
> Screenshot 2024-04-08 at 12 04 35 AM
> 

`Untitled` is the default source name when it has other information present. The reason it's saying `Untitled 99:_` is because the only present information related to the reference was chapter 99 with no specific verse nor source. It leaves it blank when no information is present but it shows what little it has if there is anything present.

**Review by thehabes — CHANGES_REQUESTED** [review]
The UI looks good and as long as the cells are showing the information that the client requested I think this is a good improvement to the view on glosses.html. 

I noticed a small problem you will have to think about as part of your scope.  This does not have the hide/show animation anymore.  I do not think you intended to remove the animation and it should work in the table view.

To see what I mean, go to https://glossing.rerum.io/glosses.html.  Character by character, waiting 1 second between each character, type "non tan".  Repeat in your interface.  You will notice the difference

**Review by thehabes — APPROVED** [review]
Animations are there!  This looks good to go.

**Pull request merged**
